file.to.parse: file.txt

#============================================================
# H2 config
#============================================================
spring:
  h2:
    console:
      enabled: true
      path: /console/
      settings:
        trace: true
        web-allow-others: false

  datasource:
    url: jdbc:h2:${user.dir}/db
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    # Create/update tables structures by Entity classes
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.jdbc.batch_size: 200
